import { NextResponse } from 'next/server';

const products = [
    { id: 1, name: "Brassière de sport sans coûture taille (S, L, W) jersey woman", price: "30€", image: "/img/femme_1.jpg" },
    { id: 2, name: "Hummel set sport sans coûture taille (S, L, W) jersey woman", price: "57€", image: "/img/femme_2.jpg" },
    { id: 3, name: "Danemark maillot Gardienne CDM Féminin 2023 taille (S, L, W)", price: "93€", image: "/img/femme_3.jpg" },
    { id: 4, name: "Hummel first T-shirt sans coûture à manches longues noir jersey", price: "23.35€", image: "/img/femme_4.jpg" },
    { id: 5, name: "Hummel débardeur classique rose désert à logo taille medium", price: "40.77€", image: "/img/femme_5.jpg" },
    { id: 6, name: "Hummel Tif soutient gorge de sport sans coûture bleu taille medium", price: "33€", image: "/img/femme_6.jpg" },
    { id: 7, name: "Hummel Core Short Noir poly woman", price: "27.55€", image: "/img/femme_7.jpg" },
    { id: 8, name: "Hummel Legging de sport sans coûture Rose", price: "53€", image: "/img/femme_8.jpg" },
    { id: 9, name: "Hummel Legging taille haute sans coûture", price: "70€", image: "/img/femme_9.jpg" },
    { id: 10, name: "Hummel Seamless T-shirt à manches longues Vert Kaki", price: "50€", image: "/img/femme_10.jpg" },
    { id: 11, name: "Hummel Cuissard Cyclisme sans coûture", price: "25€", image: "/img/femme_11.jpg" },
    { id: 12, name: "Hummel first Legging de sport sans coûtures Rose", price: "44€", image: "/img/femme_12.jpg" },
    { id: 13, name: "Hummel Sweat à capuche doux Noir", price: "39€", image: "/img/femme_13.jpg" },
    { id: 14, name: "Hummel First T-shirt sans coûture à manches courtes", price: "69€", image: "/img/femme_14.jpg" },
    { id: 15, name: "Hummel Sweat à logo à manches long Crème Blanc", price: "75€", image: "/img/femme_15.jpg" },
    { id: 16, name: "Hummel Brassière de sport à maintient lèger deep litchen green", price: "73€", image: "/img/femme_16.jpg" },
    { id: 17, name: "Hummel CamiSeamless sport athletic noir melange crème blanc", price: "32€", image: "/img/femme_17.jpg" },
    { id: 18, name: "Hummel HMLTif soutient gorge de sports sans coûture Noir Top", price: "22€", image: "/img/femme_18.jpg" },
    { id: 19, name: "Hummel T-shirt de sport dusty blue", price: "102€", image: "/img/femme_19.jpg" },
    { id: 20, name: "Hummel veste de sûrvêtement  à liséré Noir", price: "29€", image: "/img/femme_20.jpg" },
    { id: 21, name: "Hummel CamiSeamless sport grise", price: "20€", image: "/img/femme_21.jpg" },
    { id: 22, name: "Hummel T-shirt à manches courtes en coton avec logo noir", price: "62€", image: "/img/femme_22.jpg" },
    { id: 23, name: "Hummel Legging à taille haute ultra stretch avec poche latérale noir", price: "71€", image: "/img/femme_23.jpg" },
    { id: 24, name: "Hummel Legging moullant sans coûture noir sport taille medium", price: "65€", image: "/img/femme_24.jpg" },
    { id: 25, name: "Hummel hmlFirst T-shirt Seamless jersey taille (S, L) beige", price: "47€", image: "/img/femme_25.jpg" },
    { id: 26, name: "Hummel Legacy T-shirt à manches longues unisexe blanc", price: "42.47€", image: "/img/femme_26.jpg" },
    { id: 27, name: "Hummel First Seamless athletic sport black limited edition", price: "77€", image: "/img/femme_27.jpg" },
    { id: 28, name: "T-shirt Handball Femme Hummel Core Xk Noir", price: "92€", image: "/img/femme_28.jpg" },
    { id: 29, name: "Maillot de football féminin poly et coton", price: "31€", image: "/img/femme_29.jpg" },
    { id: 30, name: "Hummel T-shirt Damen Grobe weinrot XS_S taille medium", price: "21€", image: "/img/femme_30.jpg" },
    { id: 31, name: "Hummel Lifestyle collection with Aybuke Pusat", price: "91€", image: "/img/femme_31.jpg" },
    { id: 32, name: "Hummel LULU Seamless sport Scrunch black melange", price: "87€", image: "/img/femme_32.jpg" },
    { id: 33, name: "Hummel Linne black collector edition", price: "74€", image: "/img/femme_33.jpg" },
    { id: 34, name: "Legging Fur Frauen Hummel Mt Saga", price: "53€", image: "/img/femme_34.jpg" },
    { id: 35, name: "Hummel & Nike collab Pro training black edition", price: "68€", image: "/img/femme_35.jpg" },
    { id: 36, name: "Hummel Sport-bh Nathloser with Damen Cléa", price: "54€", image: "/img/femme_36.jpg" },
    { id: 37, name: "Hummel Core XK Poly T-shirt taille S_S woman", price: "52€", image: "/img/femme_37.jpg" },
    { id: 38, name: "Hummel Core sweat à capuche bleu danube", price: "66.5€", image: "/img/femme_38.jpg" },
    { id: 39, name: "Hummel Core Short de sport true blue blazing yellow", price: "56.78€", image: "/img/femme_39.jpg" },
    { id: 40, name: "Hummel HMLAUTHENTIC Korte sportsbukser true blue_yellow", price: "61€", image: "/img/femme_40.jpg" },
    { id: 41, name: "Hummel HMLAUTHENETIC Short de sport black and white", price: "78.45€", image: "/img/femme_41.jpg" },
    { id: 42, name: "Hummel HMLAUTHENTIC Sportovni bunda marine", price: "56.55€", image: "/img/femme_42.jpg" },
    { id: 43, name: "Hummel Core Short de sport white", price: "72€", image: "/img/femme_43.jpg" },
    { id: 44, name: "Hummel First SEAMLESS T-shirt de sport black", price: "67€", image: "/img/femme_44.jpg" },
    { id: 45, name: "Hummel HMLCI Puncochy black melange", price: "46€", image: "/img/femme_45.jpg" },
];

export async function GET() {
    return NextResponse.json(products);
}
